apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      creationTimestamp: null
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
      labels:
        app: {{ .Values.name }}
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                - key: "karpenter.sh/provisioner-name"
                  operator: "In"
                  values: ["preview-function"]
      containers:
        - name: {{ .Values.name }}
          image: {{.Values.ECR_URL}}/{{ .Values.name }}:{{ .Values.IMAGE_TAG }}
          command: ["yarn", "start", "-p", "3000"]
          env:
            - name: API_URL
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.name }}-cm
                  key: API_URL
            - name: NEXTAUTH_URL
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.name }}-cm
                  key: NEXTAUTH_URL
            - name: NEXTAUTH_SECRET
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.name }}-cm
                  key: NEXTAUTH_SECRET
            - name: NEXT_PUBLIC_API_URL
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.name }}-cm
                  key: NEXT_PUBLIC_API_URL
          resources:
            requests:
              memory: 200Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      imagePullSecrets:
        - name: regcred
      schedulerName: default-scheduler